name:                probabilistic-contracts
version:             0.1.0.0
github:              "githubuser/probabilistic-contracts"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/probabilistic-contracts#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- containers
- process
- temporary
- async
- unbounded-delays
- unix
- array
- random
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Parse.Lexer
    - Generate.LTL
    - Generate.MLTL
    - Generate.ProbContract
    - Parse.LTLParser
    - Parse.MLTLParser
    - Specs.LTL
    - Specs.MLTL
    - Specs.Solvable
    - Contracts.Probabilistic
    - Contracts.Refinement.Refines
    - Math
  build-tools:
    - alex
    - happy

executables:
  probabilistic-contracts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - probabilistic-contracts

tests:
  probabilistic-contracts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - probabilistic-contracts
    - hspec
